const data = {
    products: [
      {
        _id: '1',
        name: 'Nike Slim T-Shirt',
        category: 'T-Shirts',
        image: '/image/1st.jpg',
        price: 12,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Adidas Fit T-Shirt',
        category: 'T-Shirts',
        image: '/image/2nd.jpg',
        price: 10,
        countInStock: 10,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Lacoste T-Shirt',
        category: 'T-Shirts',
        image: '/image/3rd.jpg',
        price: 22,
        countInStock: 10,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Nike T-shirt',
        category: 'T-Shirts',
        image: '/image/4th.jpg',
        price: 12,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Puma Graphic T-shirt',
        category: 'T-Shirts',
        image: '/image/5th.jpg',
        price: 14,
        countInStock: 10,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Adidas Fit T-Shirt',
        category: 'T-Shirts',
        image: '/image/6th.jpg',
        price: 13,
        countInStock: 10,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;